### PR TITLE
fix: goals | prevent form submit if text is empty

### LINKED ISSUE #756: [BUG] Add new goal could be submited empty
### Describe the bug

I can submit a new goal with an empty title : 
Should we force a non empty title? 

### To Reproduce

Log in and go to settings/goals

### Expected Behavior

_No response_

### Screenshot/ Video

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Tamir198**
Closed #756, now you can`t submit the button if the text is empty : 

image

### CODE REVIEW

**Review by ArkadiK94 — CHANGES_REQUESTED** [review]
@Tamir198  When the user wants to add empty Goal the input box should become red and toast validation/error message by using the toastify library - which already installed in the project. To give indication to the user.

**Comment by Tamir198** [comment]
Now this is what you see as an error indicator : 

image


To `GoalInput` with the styled component I had to add some styles because the CSS files overrated them.

File: src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx [hunk 1]
```diff
@@ -1,28 +1,48 @@
...
 const GoalForm = () => {
     const [text, setText] = useState("");
+    const [error, setError] = useState(false);
 
     const dispatch = useDispatch();
 
     const onSubmit = (e) => {
         e.preventDefault();
+        if (text.trim() === "") {
+            toast("Cannot submit empty goal");
```
Comment (ArkadiK94) [inline src/components/Dashboard/OldDashbaord/GoalSetter/GoalForm.jsx:25]:
```suggestion
            toast.warn("Cannot submit empty goal");
```
It will look better for this toast message

**Review by ArkadiK94 — APPROVED** [review]
@Tamir198  Thanks, looks great 👍 
Only one last change.
