### PR TITLE
fix: web security | categories and route highlighting

### LINKED ISSUE #711: [FEATURE] Tags & Search Component | selection of tags
### Detailed description

Tags & Search Component - 
- remove the link with tags, 
-  make tags active when selected

### Context

more intuitive way.

### Possible implementation

- [ ] remove the link with tags - don't show the name of the tag in search box
- [ ] make tags active when selected - when user select a tag, make it orange (selected one), if multiple tags, make multiple in orange

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #758: [BUG] Filters in Web security page
### Describe the bug

The indicator color for selected filter is applied during hover only, after i select the filter and move the cursor the orange color doesnt persist .

### To Reproduce

1. Go to Web Securit page
2. Click on any of the tabs there (Topic - web labs ...)
3. Click on any of the filters in the left section 
4. the filter applies but the there's no visual indicator (no orange color on the selected filter  )

### Expected Behavior

The selected filter has a differentiating color that would persist even after hovering on the filter 

### Screenshot/ Video

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by seifnamissi**
## Fixes Issue
closes #758 (edited)

## Changes proposed

1. Categories selected are now highlighted 
2. Current routes are now highlighted

## Screenshots
image

image
()

## Code of Conduct

- [x] By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md) 🖖

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

---

You can also join our [Discord](https://discord.gg/QHBPq6xP5p) community.
Feel free to check out other cool repositories of the [Thecyberworld](https://github.com/thecyberworld).
Join the Thecyberworld GitHub Organisation by raising an [issue](https://github.com/thecyberworld/Support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) (you will be sent an invitation).

### CODE REVIEW

**Comment by ArkadiK94** [comment]
Correction: solves issue #758

File: src/components/WebSecurity/SubHeader.jsx [hunk 1]
```diff
@@ -48,7 +50,9 @@ const SubHeader = (props) => {
                                       </DropdownUl>
                                   </DropdownContainer>
                               ) : (
-                                  <NavLink to={item.link}>{item.title}</NavLink>
+                                  <NavLink to={item.link} style={{ color: currentSubPath === item.link && "#ff6b08" }}>
```
Comment (ArkadiK94) [inline src/components/WebSecurity/SubHeader.jsx:53]: Add default the "Topics" option because it appears first when we click on this page or change the redirection link to open it be `http://localhost:3000/websecurity/topics` and not `http://localhost:3000/websecurity`

image

**Review by ArkadiK94 — CHANGES_REQUESTED** [review]
Thanks for your contribution, I have two minor comments 👍

**Review by ArkadiK94 — APPROVED** [review]
@seifnamissi Thanks for your contribution 👍 
The small changes we will do later I will merge it for now.
